import type { Metadata } from 'next';
import { Press_Start_2P, Inter } from 'next/font/google';
import './globals.css';

const pressStart = Press_Start_2P({
  variable: '--font-ui',
  weight: '400',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-chat',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pressStart.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
